package:
  name: build-base
  version: 1
  epoch: 1
  description: "virtual package for builds"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - wolfi-baselayout
      - binutils
      - gcc
      - pkgconf
      - make

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - ssl_client

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"
