package:
  name: zlib
  version: 1.2.12
  epoch: 0
  description: "a library implementing the zlib compression algorithms"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MPL-2.0 AND MIT
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://packages.wolfi.dev/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - https://packages.wolfi.dev/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - perl
      - ca-certificates-bundle
      - cross-gcc-stage1
      - cross-binutils-stage1
      - cross-glibc-stage1
      - cross-linux-headers

pipeline:
  - uses: fetch
    with:
      uri: https://zlib.net/zlib-${{package.version}}.tar.gz
      expected-sha256: 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9
  - runs: |
      CHOST="${{host.triplet.gnu}}" ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --shared
  - uses: autoconf/make
  - runs: |
      make install pkgconfigdir="/usr/lib/pkgconfig" DESTDIR="${{targets.destdir}}"

subpackages:
  - name: "cross-zlib"
    pipeline:
      - runs: |
          make install pkgconfigdir="/usr/lib/pkgconfig" DESTDIR="${{targets.subpkgdir}}/usr/${{host.triplet.gnu}}"
    options:
      no-provides: true
      no-depends: true
      no-commands: true
